### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by robtweed** [alannicol/nds-qewd-mpi#1]
Alan
I notice in your mpi.js module that you're returning errors as callback("error text")

As you're directly mapping the callback function arguments to QEWD's finished() method, you need to use the standard error mechanism in QEWD, which is to return an error object.  ie you should do this instead:
    callback({error: 'error text'})

If you want to control the HTTP status code also:

   callback({
     error: 'error text',
     status: {code: 401}
    });

Hope this helps

**Comment by alannicol** [comment]
Hi Rob

Thanks for this, I will make the change.

Alan
